service: serverless-uploader

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  list:
    handler: handler.list
    events:
      - http:
          path: /list
          method: get
  upload:
    handler: handler.upload
    events:
      - http:
          path: /upload
          method: post